name: correlations
channels:
  - defaults
  - conda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.11
  - scipy
